version: '3.9'

services:
  pgdb:
    container_name: pgdb
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assigment
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  java_app:
    container_name: java_app
    build:
      context: "./assigment"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb/assigment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - pgdb

